# WARNING: Autogenerated in StateBase
# Allows making sure all flow_script variables and functions will work.
# TODO: Show stats here, like 'lines spoken' for each character.
extends StateBase
func _cond_675892952() -> bool: return score > 20 or ZONE_ENTERED.zone in [apple_area, pear_area, banana_area]
func _cond_520882869() -> bool: return ZONE_ENTERED.zone == apple_area
func _cond_2636823051() -> bool: return ZONE_ENTERED.zone == pear_area
func _cond_2090770405() -> bool: return true

####
## CHARS x2
####
var mary: CharInfo:
	get: return objects.chars[&"mary"]
var paul: CharInfo:
	get: return objects.chars[&"paul"]

####
## ITEMS x3
####
var apple: ItemInfo:
	get: return objects.items[&"apple"]
var banana: ItemInfo:
	get: return objects.items[&"banana"]
var pear: ItemInfo:
	get: return objects.items[&"pear"]

####
## ZONES x17
####
var apple_area: ZoneInfo:
	get: return objects.zones[&"apple_area"]
var banana_area: ZoneInfo:
	get: return objects.zones[&"banana_area"]
var home: ZoneInfo:
	get: return objects.zones[&"home"]
var pear_area: ZoneInfo:
	get: return objects.zones[&"pear_area"]

####
## VARS x1
####
var score: int:
	get: return objects.vars[&"score"].value
	set(v): objects.vars[&"score"].value = v

####
## QUESTS x1
####
var my_quest: QuestInfo:
	get: return objects.quests[&"my_quest"]