# WARNING: Autogenerated by REBUILD_ASSET_DB.gd
@abstract class_name AssetsBase extends Node

# Prefabs: 20
const PREFAB_BIRD := "uid://bptngmmdirjt7" # 58.787 ms
const PREFAB_MINIMAP_GENERATOR := "uid://ctgormy8gp6jh" # 23.987 ms
const PREFAB_HUMANOID := "uid://p7rqgmtls5qk" # 7.01 ms
const PREFAB_CONTROLLER := "uid://52fw605jpf2i" # 6.54 ms
const PREFAB_SIMPLE_CAR := "uid://b1e5tur6memej" # 3.871 ms
const PREFAB_SHOOTER := "uid://c0vwbb2a8p2au" # 2.481 ms
const PREFAB_CHAIR := "uid://sre8xdbu2u7v" # 1.66 ms
const PREFAB_ELEVATOR := "uid://o4q83cjjxwq6" # 1.453 ms
const PREFAB_QUADRUPED := "uid://nl47yqcvi06o" # 1.104 ms
const PREFAB_CURSOR := "uid://c06awfqjak1we" # 1.014 ms
const PREFAB_BARREL := "uid://ba47kj4lq4mm6" # 0.892 ms
const PREFAB_CAMERA_FOLLOW := "uid://clkh35bjyldwx" # 0.779 ms
const PREFAB_BOAT := "uid://b5ejo20wa8x5h" # 0.622 ms
const PREFAB_DETECTABLE_SOUND := "uid://dvms6gwqksoow" # 0.56 ms
const PREFAB_HELICOPTER := "uid://bjx4iq6iop3kt" # 0.524 ms
const PREFAB_TOGGLE := "uid://c4cky3lenwdnj" # 0.472 ms
const PREFAB_WHEEL := "uid://cobhm38x3170i" # 0.467 ms
const PREFAB_PRIMITIVE_STAIRS_2 := "uid://clrhwkbmx84kt" # 0.443 ms
const PREFAB_BIKE := "uid://cr3v2ma8nkml5" # 0.406 ms
const PREFAB_CAMERA_TOP_DOWN := "uid://c2d005ossyel5" # 0.383 ms

# Widgets: 15
const WIDGET_CAPTION := "uid://dsa17lrw23t4" # 35.18 ms
const WIDGET_QUEST_LOG := "uid://bfvfi2nwpg7lv" # 15.566 ms
const WIDGET_COMPASS_MARKERS := "uid://cciwhkqp304aa" # 9.897 ms
const WIDGET_CONFIRMATION := "uid://bpe44n5u7y2j2" # 9.124 ms
const WIDGET_SCREEN_SPACE_MARKERS := "uid://cd00x6bmm01bb" # 8.655 ms
const WIDGET_CONTEXT_MENU := "uid://cqxlxrx5yutvn" # 7.688 ms
const WIDGET_INVENTORY := "uid://cgu0c5ul5u3nn" # 7.412 ms
const WIDGET_TOAST_MANAGER := "uid://btqk7flf4ewas" # 7.083 ms
const WIDGET_INTERACTION_LABEL := "uid://bxyeghkx3u2iw" # 5.285 ms
const WIDGET_PAUSE_MENU := "uid://d4jqaawptisd8" # 3.638 ms
const WIDGET_WORLD_TIME := "uid://ceyrjlut7f1f0" # 2.532 ms
const WIDGET_SHOOTER_HUD := "uid://no8gue8b410" # 1.9 ms
const WIDGET_QUIT_POPUP := "uid://bb4ehykbh3foq" # 1.709 ms
const WIDGET_MENU := "uid://cucq8gseatpvc" # 0.61 ms
const WIDGET_RADIAL_MENU := "uid://eo5hwjki2ww0" # 0.476 ms