# WARNING: Autogenerated in WorldBase
# Allows making sure all flow_script variables and functions will work.
# TODO: Show stats here, like 'lines spoken' for each character.
extends WorldBase
func _expr_2328950157() -> void:
	if score < 20:
		archer.msg("Reset arrows.")
		print("Arrows reset.")
func _cond_5381() -> bool: return true
func _cond_520882869() -> bool: return ZONE_ENTERED.zone == apple_area
func _cond_1190937198() -> bool: return my_quest.ticked("find_apple", "find_pear", "find_banana")
func _cond_1744640919() -> bool: return ZONE_EXITED.zone in [apple_area, pear_area, banana_area]
func _cond_1916210732() -> bool: return my_quest.ticked("find_pear", "find_banana")
func _cond_2090770405() -> bool: return true
func _cond_2090815788() -> bool: return my_quest.ticked("find_apple") or my_quest.ticked("find_banana") or my_quest.ticked("find_pear")
func _cond_2590090614() -> bool: return my_quest.ticked("find_apple", "find_banana")
func _cond_2636823051() -> bool: return ZONE_ENTERED.zone == pear_area
func _cond_3056990139() -> bool: return ZONE_ENTERED.zone in [apple_area, pear_area, banana_area]
func _cond_4194837085() -> bool: return my_quest.ticked("find_apple", "find_pear")

####
## CHARS x3
####
var archer: CharInfo:
	get: return chars[&"archer"]
var mary: CharInfo:
	get: return chars[&"mary"]
var paul: CharInfo:
	get: return chars[&"paul"]

####
## ITEMS x3
####
var apple: ItemInfo:
	get: return items[&"apple"]
var banana: ItemInfo:
	get: return items[&"banana"]
var pear: ItemInfo:
	get: return items[&"pear"]

####
## ZONES x17
####
var apple_area: ZoneInfo:
	get: return zones[&"apple_area"]
var banana_area: ZoneInfo:
	get: return zones[&"banana_area"]
var home: ZoneInfo:
	get: return zones[&"home"]
var pear_area: ZoneInfo:
	get: return zones[&"pear_area"]

####
## STATS x1
####
var score: float:
	get: return stats[&"score"].value
	set(v): stats[&"score"].value = v

####
## QUESTS x1
####
var my_quest: QuestInfo:
	get: return quests[&"my_quest"]