@tool
class_name EditorRebuildAssetDB extends EditorScript

const PATH_AUTOGEN_ASSET_BASE := "res://_autogen_/_assets_base_.gd"

func _run() -> void:
	var ass := AssetsDB.new()
	ass.reload()
	ResourceSaver.save(ass, "res://assets/assets.tres")
	EditorInterface.get_resource_filesystem().scan()
	EditorInterface.get_resource_filesystem().update_file("res://assets/assets.tres")
	EditorInterface.get_resource_filesystem().reimport_files(["res://assets/assets.tres"])
	
	var code := [
		"# WARNING: Autogenerated by REBUILD_ASSET_DB.gd",
		"@abstract class_name AssetsBase extends Node"
	]
	var prefabs := []
	var widgits := []
	
	for scene_id in ass.scenes:
		var scene_path := "res://scenes".path_join(ass.scenes[scene_id])
		var const_name := scene_id.to_upper()
		var uid := ResourceUID.path_to_uid(scene_path)
		var time := Time.get_ticks_usec()
		var packed: PackedScene = load(scene_path)
		if not packed: continue
		var scene := packed.instantiate()
		time = Time.get_ticks_usec() - time
		if scene_path.begins_with("res://scenes/prefabs"):
			prefabs.append(["const PREFAB_%s := \"%s\" # %s ms" % [const_name, uid, time / 1000.0], time])
		elif scene is Widget:
			widgits.append(["const WIDGIT_%s := \"%s\" # %s ms" % [const_name, uid, time / 1000.0], time])
		scene.free()
	
	prefabs.sort_custom(func(a, b): return a[1] > b[1])
	widgits.sort_custom(func(a, b): return a[1] > b[1])
	
	# Flatten array to strings.
	prefabs = ["\n# Prefabs: %s" % prefabs.size()] + prefabs.map(func(x): return x[0])
	widgits = ["\n# Widgits: %s" % widgits.size()] + widgits.map(func(x): return x[0])
	
	var file := FileAccess.open(PATH_AUTOGEN_ASSET_BASE, FileAccess.WRITE)
	file.store_string("\n".join(code + prefabs + widgits))
	file.close()

func _get_node_script(state: SceneState) -> GDScript:
	var prop_list := state.get_node_property_count(0)
	for i in prop_list:
		if state.get_node_property_name(0, i) == "script":
			return state.get_node_property_value(0, i)
	return null
