# WARNING: Autogenerated by REBUILD_ASSET_DB.gd
@abstract class_name AssetsBase extends Node

# Prefabs 19
const PREFAB_MINIMAP_GENERATOR := "uid://ctgormy8gp6jh" # 171.882 ms
const PREFAB_HUMANOID := "uid://p7rqgmtls5qk" # 145.736 ms
const PREFAB_SIMPLE_CAR := "uid://b1e5tur6memej" # 8.765 ms
const PREFAB_BIRD := "uid://bptngmmdirjt7" # 7.707 ms
const PREFAB_SHOOTER := "uid://c0vwbb2a8p2au" # 3.637 ms
const PREFAB_CONTROLLER_PLAYER := "uid://52fw605jpf2i" # 3.577 ms
const PREFAB_TOGGLE := "uid://c4cky3lenwdnj" # 3.529 ms
const PREFAB_CAMERA_FOLLOW := "uid://clkh35bjyldwx" # 1.756 ms
const PREFAB_BARREL := "uid://ba47kj4lq4mm6" # 1.216 ms
const PREFAB_CURSOR := "uid://c06awfqjak1we" # 1.051 ms
const PREFAB_PRIMITIVE_STAIRS_2 := "uid://clrhwkbmx84kt" # 1.01 ms
const PREFAB_ITEM := "uid://s3xtrx0yba71" # 0.972 ms
const PREFAB_CAMERA_TOP_DOWN := "uid://c2d005ossyel5" # 0.914 ms
const PREFAB_BIKE := "uid://cr3v2ma8nkml5" # 0.897 ms
const PREFAB_QUADRUPED := "uid://nl47yqcvi06o" # 0.806 ms
const PREFAB_BOAT := "uid://b5ejo20wa8x5h" # 0.736 ms
const PREFAB_DETECTABLE_SOUND := "uid://dvms6gwqksoow" # 0.363 ms
const PREFAB_HELICOPTER := "uid://bjx4iq6iop3kt" # 0.328 ms
const PREFAB_WHEEL := "uid://cobhm38x3170i" # 0.32 ms

# Widgits 8
const WIDGIT_CAPTION := "uid://dsa17lrw23t4" # 3.063 ms
const WIDGIT_INVENTORY := "uid://cgu0c5ul5u3nn" # 2.424 ms
const WIDGIT_QUEST_LOG := "uid://bfvfi2nwpg7lv" # 1.816 ms
const WIDGIT_CONTEXT_MENU := "uid://cqxlxrx5yutvn" # 0.518 ms
const WIDGIT_INTERACTION_LABEL := "uid://bxyeghkx3u2iw" # 0.491 ms
const WIDGIT_MENU := "uid://cucq8gseatpvc" # 0.448 ms
const WIDGIT_TOAST_MANAGER := "uid://btqk7flf4ewas" # 0.43 ms
const WIDGIT_RADIAL_MENU := "uid://eo5hwjki2ww0" # 0.391 ms
